/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

/* Info:
 * SVC é usado para que o usuário de um sistema (geralmente rtos) possa solicitar fazer acesso a recursos privilegiados
 * para o kernel do sistema.
 */

int main(void)
{
	__asm volatile ("SVC #25");  // Valor imediato 8 é o opcode do SVC.

	//	register uint32_t data __asm("r0");
	//	printf("data = %ld\n", data);  // 29
	//	int y = 1;
	//	int x = 1 + y;
	//	printf("data = %ld\n", data);  // 11 - cuidado com variáveis criadas nos registros, elas podem mudar inesperadamente

	uint32_t data;
	__asm volatile ("MOV %0, R0":"=r"(data));
	printf("data = %ld\n", data);

	for(;;);
}

__attribute__((naked)) void SVC_Handler(void){
	__asm("MRS R0,MSP");
	__asm("B SVC_Handler_c");  // O valor de r0 será tomado como argumento da função
}

void SVC_Handler_c(uint32_t *pBaseOfStackFrame){
	printf("In SVC Handler\n");
	uint8_t *pReturn_addr = (uint8_t *)pBaseOfStackFrame[6];

	// decremment the return address by 2 to point to
	// opcode of the SVC instruction in the program memory
	pReturn_addr -= 2;  // Pega o opcode anterior

	// Extract the SVC number (LSByte of the opcode)
	uint8_t svc_number = *pReturn_addr;
	printf("SVC number is : %d\n", svc_number);

	// Enviando o svc_number incrementado de 4 de volta para thread mode usando o r0 do stackframe
	svc_number += 4;
	pBaseOfStackFrame[0] = svc_number;

}









