/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int main(void)
{
	int16_t res, arg1, arg2;

	uint8_t svc_num;

	arg1 = 90;
	arg2 = 5;

	svc_num = 4;

	switch (svc_num){
		case 1:  // +
			__asm volatile ("MOV R1,%0": : "r"(arg1));
			__asm volatile ("MOV R2,%0": : "r"(arg2));
			__asm volatile ("SVC #1");
			__asm volatile ("MOV %0, R0":"=r"(res));
			break;
		case 2:  // -
			__asm volatile ("MOV R1,%0": : "r"(arg1));
			__asm volatile ("MOV R2,%0": : "r"(arg2));
			__asm volatile ("SVC #2");
			__asm volatile ("MOV %0, R0":"=r"(res));
			break;
		case 3:  // *
			__asm volatile ("MOV R1,%0": : "r"(arg1));
			__asm volatile ("MOV R2,%0": : "r"(arg2));
			__asm volatile ("SVC #3");
			__asm volatile ("MOV %0, R0":"=r"(res));
			break;
		case 4:  // /
			__asm volatile ("MOV R1,%0": : "r"(arg1));
			__asm volatile ("MOV R2,%0": : "r"(arg2));
			__asm volatile ("SVC #4");
			__asm volatile ("MOV %0, R0":"=r"(res));
			break;
	}
	printf("result = %d\n", res);

	for(;;);
}


__attribute__((naked)) void SVC_Handler(void){
	__asm("MRS R0,MSP");
	__asm("B SVC_Handler_c");  // O valor de r0 será tomado como argumento da função
}

void SVC_Handler_c(uint32_t *pBaseOfStackFrame, int16_t arg1, int16_t arg2){

	int16_t res;
	uint8_t *pReturn_addr = (uint8_t *)pBaseOfStackFrame[6];
	pReturn_addr -= 2;
	uint8_t svc_num = *pReturn_addr;

	switch (svc_num){
		case 1:
			res = arg1 + arg2;
			break;
		case 2:
			res = arg1 - arg2;
			break;
		case 3:
			res = arg1 * arg2;
			break;
		case 4:
			res = arg1 / arg2;
			break;
	}

	*pBaseOfStackFrame  = res; // Escrevendo em R0 do stackframe

}

