/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

// Essa função é executada no THREAD MODE do processador
void generate_interrupt(){
	uint32_t *pSTIR = (uint32_t *)0xE000EF00;
	uint32_t *pISER0 = (uint32_t *)0xE000E100;

	// Enable IRQ3 interrupt
	*pISER0 |= (1 << 3);  // Ao tentar alterar esse registro no modo THREAD, sem privilégio, uma exception será gerada

	// Generate an interrupt from software for IRQ3
	*pSTIR = (3 & 0x1FF);
}

void change_access_level_unpriv(void){
	// read
	__asm volatile("MRS R0,CONTROL");
	// modify
	__asm volatile("ORR R0,R0,#0x01");
	// write
	__asm volatile("MSR CONTROL,R0");
}

// Essa função é executada no THREAD MODE do processador
int main(void){
	printf("In thread mode : before interrupt\n");

	void (*fun_ptr)(void);  // Pointer de funcão

	// fun_ptr = change_access_level_unpriv;
	fun_ptr = (void *)0x80001e8;
	fun_ptr();  // Causará uma exception, pois o bit 0 do PC será carregado no T bit e mudará para ARM Instruction Set

	printf("In thread mode : after interrupt\n");
	for(;;);
}

// Essa função (ISR) executa no HANDLER MODE do processador
void RTC_WKUP_IRQHandler(void){
	printf("In handler mode : ISR\n");
}

void HardFault_Handler(void){
	printf("Hard fault detected\n");
	while(1);
}




