/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define SRAM_START (0x20000000U)
#define SRAM_SIZE (128 * 1204)
#define SRAM_END ((SRAM_START) + (SRAM_SIZE))
#define STACK_START (SRAM_END)

#define STACK_MSP_START (STACK_START)
#define STACK_MSP_END (STACK_MSP_START + 512)
#define STACK_PSP_START (STACK_MSP_END)

int fun_add(int a, int b, int c, int d){
	return a + b + c + d;
}

__attribute__((naked)) void change_sp_to_psp(void){

	// Assembly macros
	__asm volatile(".equ SRAM_END, (0x20000000 + (128 * 1024))");
	__asm volatile(".equ PSP_START, (SRAM_END - 512)");

	// Inicializa o valor de PSP para STACK_PSP_START
	__asm volatile("LDR R0,=PSP_START");
	__asm volatile("MSR PSP,R0");

	// Muda o stack pointer para PSP
	__asm volatile("MOV R0,#0x02");
	__asm volatile("MSR CONTROL, R0");

	// return
	__asm volatile ("BX LR");

}

void generate_exception(void){
	__asm volatile("SVC #0x2");
}

int main(void)
{
	change_sp_to_psp();

    int ret;

    ret = fun_add(1, 4, 5, 6);

    printf("result = %d\n", ret);

    generate_exception();

	for(;;);
}

void SVC_Handler(void){
	printf(" in SVC_Handler\n");
}










