/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"
#include "led.h"

TCB_t user_tasks[MAX_TASKS] = {
		{.psp_value=T0_STACK_START, .block_count=0, .current_state=TASK_RUNNING_STATE, .task=task0},
		{.psp_value=T1_STACK_START, .block_count=0, .current_state=TASK_RUNNING_STATE, .task=task1},
		{.psp_value=T2_STACK_START, .block_count=0, .current_state=TASK_RUNNING_STATE, .task=task2},
		{.psp_value=T3_STACK_START, .block_count=0, .current_state=TASK_RUNNING_STATE, .task=task3},
		{.psp_value=IDLE_STACK_START, .block_count=0, .current_state=TASK_RUNNING_STATE, .task=idle_task}
};
uint8_t current_task = 0;

/* Info:
 * O contexto de uma task é composto por:
 * Stack Frame 1 (SF1): É salvo e recuperado automaticamente pelo processador, composto por xPSR, PC, LR, R12, R3, R2, R1, R0
 * Stack Frame 2 (SF2): Deve ser salvo pelo programador dentro da interrupção, composto por: R11, R10, R9, R8, R7, R6, R5, R4
 * PSP de cada task pode ser salvo em variáveis globais
 *
 * Antes de uma task ser executada pela primeira vez, ela não terá um contexto, logo, o programador deve armazenar
 * dummy data no stack de cada task para inicializa-las.
 * R0 - R12 podem ser inicializadas com 0 ou qualquer outro valor.
 * xPSR - É importante nesse registro que o Tbit seja 1, o resto não importa. Pode ser inicializado com 0x01000000.
 * PC - Endereço da task, tenha certeza de que o lsb seja 1 (para que o tbit seja 1)
 * LR - EXC_RETURN 0xFFFFFFFD Retorna para o threadmode usando PSP
 */


int main(void)
{
	enable_processor_faults();
	init_scheduler_stack(SCHED_STACK_START);
	init_tasks_stack();
	led_init_all();
	init_systick_timer(TICK_HZ);

	switch_sp_to_psp();
	task0();

	for(;;);
}

void task0(void){
	for(;;){
		led_on(LED_GREEN);
		task_delay(1000);
		led_off(LED_GREEN);
		task_delay(1000);
	}
}

void task1(void){
	for(;;){
		led_on(LED_ORANGE);
		task_delay(500);
		led_off(LED_ORANGE);
		task_delay(500);
	}
}

void task2(void){
	for(;;){
		led_on(LED_BLUE);
		task_delay(250);
		led_off(LED_BLUE);
		task_delay(250);
	}
}

void task3(void){
	for(;;){
		led_on(LED_RED);
		task_delay(125);
		led_off(LED_RED);
		task_delay(125);
	}
}

void idle_task(void){
	for(;;);
}

void task_delay(uint32_t tick_count){
	/* Info:
	 * É uma boa prática desativar as interrupções quando modificamos variáveis
	 * globais compartilhadas entre interrupções e thread mode
	 */
	// Desativa as interrupções
	INTERRUPT_DISABLE();

	user_tasks[current_task].block_count = tick_count;
	user_tasks[current_task].current_state = TASK_BLOCKED_STATE;
	// Pend the pendSV
	uint32_t *pICSR = (uint32_t *)0xE000ED04;
	*pICSR |= 1 << 28;

	// Ativa as interrupções
	INTERRUPT_ENABLE();
}

__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack){
	__asm volatile("MSR MSP,R0");
	__asm volatile("BX LR");  // Retorna para main
}

void init_tasks_stack(void){

	uint32_t *pPSP;
	for(int i = 1; i < MAX_TASKS; i++){
		pPSP = (uint32_t *)user_tasks[i].psp_value;
		pPSP--;
		*pPSP = 0x01000000;  // xPSR
		pPSP--;
		*pPSP = (uint32_t)user_tasks[i].task;  // PC
		pPSP--;
		*pPSP = 0xFFFFFFFD;  // LR

		for(int j = 0; j < 13; j++){
			pPSP--;
			*pPSP = 0; // Coloca 0 em R0 a R12
		}
		user_tasks[i].psp_value = (uint32_t)pPSP;
	}
}

void init_systick_timer(uint32_t tick_hz){
	/* Info:
	 * Configuração do systick Timer.
	 * (count_value + 1) é o valor no qual o clock principal será dividido para obter o valor de clock desejado para o timer
	 * ex: count_value = 99   ->   count_value + 1 = 100   ->   freq tick = clock principal / 100
	 *
	 */

	// Inicializando o valor do SysTick Reload Value Register (funciona como um divisor do clock)
	uint32_t *pSRVR = (uint32_t *)0xE000E014;
	uint32_t count_value = SYSTICK_TIM_CLK / tick_hz - 1;  // -> freq tick = clock principal / (count_value + 1) -> freq tick = tick_hz
	*pSRVR = count_value;

	// Configurações
	uint32_t *pSCSR = (uint32_t *)0xE000E010;  // SysTick Control and Status Register
	*pSCSR |= 0x07;  // Processor clock source / SysTick excpetion enabled / Counter Enable
}

uint32_t get_psp_value(void){
	return user_tasks[current_task].psp_value;
}

void save_psp_value(uint32_t current_psp_value){
	user_tasks[current_task].psp_value = current_psp_value;
}

void update_next_task(void){
	for (int i = 0; i < (MAX_TASKS - 1); i++){
		current_task++;
		current_task %= (MAX_TASKS - 1);
		if (user_tasks[current_task].current_state == TASK_RUNNING_STATE)
			break;
		if (i == (MAX_TASKS - 2)){
			current_task = (MAX_TASKS - 1);
		}
	}
}

void update_block_count_ticks(void){
	for(int i = 0; i < (MAX_TASKS - 1); i++){
		if(user_tasks[i].current_state == TASK_BLOCKED_STATE){
			user_tasks[i].block_count--;
			if(user_tasks[i].block_count == 0)
				user_tasks[i].current_state = TASK_RUNNING_STATE;
		}
	}
}

__attribute__((naked)) void switch_sp_to_psp(void){
	// 1. initialize the PSP with TASK0 stack start
	__asm volatile ("PUSH {LR}");  // Preserva LR no MSP, que conecta de volta a main
	__asm volatile ("BL get_psp_value");
	__asm volatile ("MSR PSP,R0");
	__asm volatile ("POP {LR}");
	// 2. change SP to PSP using CONTROL register
	__asm volatile ("MOV R0,#0x02");
	__asm volatile ("MSR CONTROL,R0");
	__asm volatile ("BX LR");

}

void SysTick_Handler(void){
	uint32_t *pICSR = (uint32_t *)0xE000ED04;
	update_block_count_ticks();
	*pICSR |= 1 << 28;  // Set PendSV
}

__attribute__((naked)) void PendSV_Handler(void){
	// Save the context of current task

	// 1. Get current running task's PSP value
	__asm volatile ("MRS R0,PSP");
	// 2. Using that PSP value store SF2 (R4 to R11)
	__asm volatile ("STMDB R0!,{R4-R11}");  // decrementa primeiro, armazena depois.
	// 3. Save the current value of PSP
	__asm volatile ("PUSH {LR}");  // Preserva LR no MSP, que conecta de volta a main
	__asm volatile ("BL save_psp_value");


	// Retrieve the context of next task
	// 1. Decide next task to run
	__asm volatile ("BL update_next_task");
	// 2. Get its past PSP value
	__asm volatile ("BL get_psp_value");
	// 3. Using that PSP value retrieve SF2 (R4 to R11)
	__asm volatile ("LDMIA R0!,{R4-R11}");  // armazena primeiro, incrementa depois.
	// 4. Update PSP and exit
	__asm volatile ("MSR PSP, R0");
	__asm volatile ("POP {LR}");  // Recupera LR
	__asm volatile ("BX LR");
}

void enable_processor_faults(void){
	//1. Enable all configurable exceptions like usage fault, mem manage fault and bus fault
	uint32_t *pSHCSR = (uint32_t *)0xE000ED24;
	*pSHCSR |= 1 << 16;  // MEMFAULTENA
	*pSHCSR |= 1 << 17;  // BUSFAULTENA
	*pSHCSR |= 1 << 18;  // USGFAULTENA
}

void HardFault_Handler(void){
	printf("Exception : Hardfault\n");
	while(1);
}

void MemManage_Handler(void){
	printf("Exception : MemManage\n");
	while(1);
}

void BusFault_Handler(void){
	printf("Exception : BusFault\n");
	while(1);
}

__attribute__ ((naked)) void UsageFault_Handler(void){
	// Extraimos o endereço do MSP que é o endereço base do stack frame do thread mode
	__asm ("MRS r0,MSP");
	__asm ("B UsageFault_Handler_c");  // r0 é o argumento da função chamada, assim como é padrão em todas as funções
}

void UsageFault_Handler_c(uint32_t *pBaseStackFrame){

	uint32_t *pUFSR = (uint32_t *)0xE000ED2A;
	printf("Exception : UsageFault\n");
	printf("UFSR = %lX\n", *pUFSR);
	printf("BaseStackFrame = %p\n", pBaseStackFrame);
	printf("Value of R0 = %lX\n", pBaseStackFrame[0]);
	printf("Value of R1 = %lX\n", pBaseStackFrame[1]);
	printf("Value of R2 = %lX\n", pBaseStackFrame[2]);
	printf("Value of R3 = %lX\n", pBaseStackFrame[3]);
	printf("Value of R12 = %lX\n", pBaseStackFrame[4]);
	printf("Value of LR = %lX\n", pBaseStackFrame[5]);
	printf("Value of PC = %lX\n", pBaseStackFrame[6]);
	printf("Value of XPSR = %lX\n", pBaseStackFrame[7]);

	while(1);
}







