/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define IRQNO_TIMER2 28
#define IRQNO_I2C1 31

#define NVIC_IPRBase (0xE000E400)  // Interrupt Priority Register Base Addr
#define NVIC_ISERBase (0xE000E100)  // Interrupt Set-enable Register Base Addr
#define NVIC_ISPRBase (0xE000E200)  // Interrupt Set-pending Register Base Addr

void configure_priority_for_irqs(uint8_t irq_no, uint8_t priority_value){
	*((uint8_t *)(NVIC_IPRBase + irq_no)) = priority_value;
}

int main(void){

	// 1. Configure the priority for the peripherals
	configure_priority_for_irqs(IRQNO_TIMER2, 0x80);
	configure_priority_for_irqs(IRQNO_I2C1, 0x80);

	// 2. Set the interrupt pending bit in the NVIC PR
	uint32_t *pNVIC_ISPRBase = (uint32_t *)NVIC_ISPRBase;
	*pNVIC_ISPRBase |= (1 << IRQNO_I2C1);

	// 3. Enable the IRQs in NVIC ISER
	uint32_t *pNVIC_ISERBase = (uint32_t *)NVIC_ISERBase;
	*pNVIC_ISERBase |= (1 << IRQNO_I2C1) | (1 << IRQNO_TIMER2);

	for(;;);
}

void TIM2_IRQHandler(void){
	printf("[TIM2_IRQHandler]\n");
}

void I2C1_EV_IRQHandler(void){
	uint32_t *pNVIC_ISPRBase = (uint32_t *)NVIC_ISPRBase;
	*pNVIC_ISPRBase |= (1 << IRQNO_TIMER2);
	printf("[I2C_EV_IRQHandler]\n");
	while(1);
}

/* Info:
 * Caso ambas as interrupções tenham a mesma prioridade e ocorram exatamente ao mesmo tempo,
 * a de número menor (IRQNO_TIMER2 28 < IRQNO_I2C1 31) será executada primeiro.
 * Caso ambas as interrupções tenham a mesma prioridade, uma interrupção só será executada
 * quando a outra terminar de executar
 *
 * Caso uma interrupção tenha prioridade superior a outra, ela será executada de imediato, mesmo
 * que a outra esteja no meio de seu processo de execução (a de maior prioridade interrompe a de menor).
 * A de menor continuará sua execução após a de maior prioridade terminar.
 *
 *
 */



